Repository FRONTENDBOOTCAMP-12th/1st-LionPlace, pull requests merged in 2024-12, with the labels that each got.

#13 💄 : sass 관련 파일 등록
  src/assets/.gitkeep
  src/assets/sass/base.scss
  src/assets/sass/font.scss
  src/assets/sass/mixins.scss
  src/assets/sass/reset.scss
  src/assets/sass/variables.scss
  src/main.scss
  src/styles/reset.scss
Labels: 💼 Feature, 🟡 Priority : Medium

#15 Feature/navigation
  index.html
Labels: 💼 Feature

#16 Feature/navitems컴포넌트 생성
  docs/assets/modulepreload-polyfill-B5Qt9EMX.js
  docs/assets/navitems-BZ3Bc829.css
  docs/assets/navitems-DEPcvA6s.js
  docs/index.html
  docs/src/layout/navitems/index.html
  index.html
  src/assets.d.ts
  src/assets/navitems/Map.svg
  src/assets/navitems/car.svg
  src/assets/navitems/my.svg
  src/assets/navitems/save.svg
  src/assets/navitems/subway.svg
  src/layout/.gitkeep
  src/layout/navitems/index.html
  src/layout/navitems/index.js
  src/layout/navitems/navitems.scss
  src/layout/navitems/navitems.ts
  src/styles/reset.scss
  src/styles/sass/base.scss
  src/styles/sass/font.scss
  src/styles/sass/mixins.scss
  src/styles/sass/reset.scss
  src/styles/sass/variables.scss
  tsconfig.json
  vite.config.js
Labels: 💼 Feature, 🟡 Priority : Medium

#25 ✨ : Feature/reserved component 생성
  _main-template.html
  src/@types/scss.d.ts
  src/assets/reservation-types/app.svg
  src/assets/reservation-types/date.svg
  src/assets/reservation-types/hospital.svg
  src/assets/reservation-types/scissors.svg
  src/assets/reservation-types/spoon.svg
  src/assets/reservation-types/ticket.svg
  src/components/navigation/navigation.ts
  src/components/reservation/reservation-toggle.scss
  src/components/reservation/reservation-toggle.ts
  src/components/reservation/reservation-types.scss
  src/components/reservation/reservation-types.ts
  src/styles/sass/variables.scss
  vite.config.js
Labels: 💼 Feature, 🟡 Priority : Medium

#37 🔧: Feature/visit-record 페이지 추가
  src/pages/visit-record/index.html
  src/pages/visit-record/visit-record.scss
  vite.config.js
Labels: 💼 Feature

#39 Feature/review-main-page
  src/components/category/category.scss
  src/components/horizon-image/horizon-image.scss
  src/components/horizon-image/horizon-image.ts
  src/components/image-field-feed/image-field-feed.ts
  src/components/image-field-feed/img-field-feed.scss
  src/components/theme/theme.scss
  src/components/theme/theme.ts
  src/layout/navitems/navitems.scss
  src/layout/time-gps/timegps.ts
  src/pages/review/index.html
  src/pages/review/review.scss
  src/pages/review/review.ts
  vite.config.js
Labels: 🛠️ BugFix, ♿ A11y, 💼 Feature, 🔴 Priority : High, 🧹 Refactor

#41 Feature/reserved main page
  src/assets/images/reservation-calendar.svg
  src/components/reservation/reservation-toggle.scss
  src/components/reservation/reservation-visit-list.scss
  src/components/reservation/reservation-visit-list.ts
  src/pages/reserved/index.html
  src/pages/reserved/index.js
  src/pages/reserved/reserved.js
  src/pages/reserved/reserved.scss
Labels: 💼 Feature, 🔴 Priority : High

#46 Fix/bom ellen refactoring
  src/components/reservation/reservation-types.ts
  src/components/reservation/reservation-visit-list.ts
  src/layout/navitems/index.html
  src/pages/reserved/index.html
  src/pages/reserved/reserved.scss
Labels: ♿ A11y, 🟡 Priority : Medium, 🧹 Refactor

#51 Feature/order page component
  public/hot-mint-choco.png
  src/assets/images/footer-language.svg
  src/components/footer/footer.scss
  src/components/footer/footer.ts
  src/components/order-page/order-table.scss
  src/components/order-page/order-table.ts
  src/pages/reserved/index.html
  src/pages/reserved/reserved.scss
Labels: 💼 Feature, 🟡 Priority : Medium

#53 Feature/order page organize
  src/components/index.js
  src/components/reservation/reservation-toggle.scss
  src/components/reservation/reservation-toggle.ts
  src/pages/order/index.html
  src/pages/order/order.scss
Labels: 💼 Feature, 🔴 Priority : High

#55 Fix/bom ellen refactoring
  src/components/reservation/reservation-toggle.ts
  src/components/reservation/reservation-types.ts
  src/layout/navitems/navitems.ts
Labels: ♿ A11y, 🔴 Priority : High, 🧹 Refactor

#60 Feature/reserved show more component
  src/assets/reserved-more-show/hospital.svg
  src/assets/reserved-more-show/scissor.svg
  src/assets/reserved-more-show/video.svg
  src/components/index.js
  src/components/reserved-show-more/reserved-more-review-textonly.scss
  src/components/reserved-show-more/reserved-more-review-textonly.ts
  src/components/reserved-show-more/reserved-more-review.scss
  src/components/reserved-show-more/reserved-more-review.ts
  src/components/reserved-show-more/reserved-more-title.scss
  src/components/reserved-show-more/reserved-more-title.ts
  src/pages/reserved/index.html
  src/pages/reserved/reserved.js
  src/pages/reserved/reserved.scss
Labels: 💼 Feature, 🟡 Priority : Medium

#62 ♻️ : 예약/주문 페이지 리팩토링
  src/components/reservation/reservation-toggle.ts
  src/components/reservation/reservation-types.scss
  src/components/reservation/reservation-types.ts
  src/components/reserved-show-more/reserved-more-review-textonly.scss
  src/components/reserved-show-more/reserved-more-review.ts
  src/components/reserved-show-more/reserved-more-title.scss
  src/components/reserved-show-more/reserved-more-title.ts
  src/pages/order/index.html
  src/pages/reserved/index.html
  src/pages/reserved/reserved.scss
  vite.config.js
Labels: 🟡 Priority : Medium, 🧹 Refactor

#67 Feature/reserved page database connect
  src/@types/type.d.ts
  src/assets/reserved-more-show/hospital.svg
  src/assets/reserved-more-show/restaurant.svg
  src/assets/reserved-more-show/video.svg
  src/components/reservation/reservation-types.ts
  src/components/reservation/reservation-visit-list.ts
  src/components/reserved-show-more/reserved-more-review.scss
  src/components/reserved-show-more/reserved-more-review.ts
  src/components/reserved-show-more/reserved-more-title.scss
  src/components/reserved-show-more/reserved-more-title.ts
  src/pages/reserved/index.html
  src/pages/reserved/reserved.js
  src/pages/reserved/reserved.ts
Labels: 💼 Feature, 🔴 Priority : High, 🧹 Refactor

#72 ✨ : 로딩 스피너 제작
  src/components/index.js
  src/components/loading-spinner/loading-spinner.scss
  src/components/loading-spinner/loading-spinner.ts
Labels: 💼 Feature, 🟡 Priority : Medium

#74 Feature/visit like component
  src/@types/type.d.ts
  src/assets/visit-like/keyword-more-btn.svg
  src/assets/visit-like/popup-close-btn.svg
  src/assets/visit-like/review-photo-btn.svg
  src/components/feed/post-list.ts
  src/components/index.js
  src/components/profile-all/profile-all.ts
  src/components/visit-like/index.html
  src/components/visit-like/index.js
  src/components/visit-like/like-keyword-check.ts
  src/components/visit-like/like-recommend.ts
  src/components/visit-like/visit-like-popup.ts
  src/components/visit-like/visit-like.scss
  src/components/visit-like/visit-review.ts
  src/components/visit-record/index.html
  src/components/visit-record/visit-record-complete.ts
  src/components/visit-record/visit-record-noreview.ts
  src/components/visit-record/visit-record.scss
  src/components/visit-record/visit-records.ts
  src/pages/visit-like/index.html
  vite.config.js
Labels: 💼 Feature
